services:
  postgres:
    image: postgres:15
    ports:
      - "30432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: messenger
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "messenger"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=5432 user=postgres password=test dbname=messenger sslmode=disable
      - GOOSE_COMMAND=up
      - GOOSE_MIGRATION_DIR=/migrations
    volumes:  
          - ./migrations:/migrations:ro
    restart: "no"

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway-final
    container_name: gateway
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - auth
      - websocket

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth-final
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./auth_service/config:/app/auth_service/config:ro

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
      target: websocket-final
    container_name: websocket_manager
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./websocket_manager/config:/app/websocket_manager/config:ro